# Generated by Django 6.0.1 on 2026-01-22 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits, optionally starting with +', regex='^\\+?\\d{10,10}$')]),
        ),
    ]
