# Generated by Django 6.0.1 on 2026-01-23 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='area',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='timezone',
        ),
    ]
