# Generated by Django 6.0.1 on 2026-01-27 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0003_businesscategory_alter_businessprofile_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('product_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('digital', 'Digital')], max_length=20)),
                ('target_audience', models.CharField(max_length=255)),
                ('key_benefits', models.TextField(help_text='Comma separated benefits')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.businessprofile')),
            ],
        ),
    ]
